CREATE TABLE IF NOT EXISTS `sys_user` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `employee_no` varchar(50) NOT NULL COMMENT '工号/登录账号',
    `password_hash` varchar(255) NOT NULL COMMENT '登录密码密文',
    `name` varchar(50) NOT NULL COMMENT '姓名',
    `role_code` varchar(50) NOT NULL COMMENT '角色编码：admin/planner/operator/inspector/repair',
    `role_name` varchar(50) NOT NULL COMMENT '角色名称',
    `department` varchar(50) DEFAULT NULL COMMENT '部门/班组',
    `position` varchar(50) DEFAULT NULL COMMENT '岗位',
    `phone` varchar(20) DEFAULT NULL COMMENT '手机号',
    `skill_level` varchar(50) DEFAULT NULL COMMENT '技能等级',
    `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态：0=停用 1=启用',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_sys_user_employee_no` (`employee_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统用户表';

CREATE TABLE IF NOT EXISTS `product_model` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `model_code` varchar(50) NOT NULL COMMENT '型号编码',
    `model_name` varchar(100) NOT NULL COMMENT '型号名称',
    `category` varchar(50) DEFAULT NULL COMMENT '产品类别',
    `configuration_desc` varchar(800) DEFAULT NULL COMMENT '外壳、PCB、轴体、键帽、灯效、连接方式等配置摘要',
    `firmware_version` varchar(50) DEFAULT NULL COMMENT '固件/功能版本',
    `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态：0=停用 1=启用',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `remark` varchar(200) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_product_model_model_code` (`model_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='产品型号表';

CREATE TABLE IF NOT EXISTS `material` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `material_code` varchar(50) NOT NULL COMMENT '物料编码',
    `material_name` varchar(100) NOT NULL COMMENT '物料名称',
    `specification` varchar(200) DEFAULT NULL COMMENT '规格型号',
    `material_type` tinyint NOT NULL COMMENT '物料类型：1=零部件 2=辅料 3=半成品 4=成品',
    `unit` varchar(20) DEFAULT NULL COMMENT '计量单位',
    `supplier` varchar(100) DEFAULT NULL COMMENT '供应商/来源',
    `barcode` varchar(100) DEFAULT NULL COMMENT '物料条码或批次条码',
    `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态：0=停用 1=启用',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_material_material_code` (`material_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物料表';

CREATE TABLE IF NOT EXISTS `product_bom` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `product_model_id` bigint NOT NULL COMMENT '产品型号ID',
    `bom_version` varchar(20) NOT NULL COMMENT 'BOM版本',
    `material_id` bigint NOT NULL COMMENT '物料ID',
    `quantity` decimal(10,3) NOT NULL COMMENT '标准用量',
    `unit` varchar(20) DEFAULT NULL COMMENT '计量单位',
    `sequence_no` int DEFAULT NULL COMMENT 'BOM行序号',
    `effective_date` date DEFAULT NULL COMMENT '生效日期',
    `expire_date` date DEFAULT NULL COMMENT '失效日期',
    `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态：0=停用 1=启用',
    `remark` varchar(200) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    KEY `idx_product_bom_model` (`product_model_id`),
    KEY `idx_product_bom_material` (`material_id`),
    CONSTRAINT `fk_product_bom_model` FOREIGN KEY (`product_model_id`) REFERENCES `product_model` (`id`),
    CONSTRAINT `fk_product_bom_material` FOREIGN KEY (`material_id`) REFERENCES `material` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='产品BOM表';

CREATE TABLE IF NOT EXISTS `process_route` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `product_model_id` bigint NOT NULL COMMENT '产品型号ID',
    `route_version` varchar(20) NOT NULL COMMENT '工艺路线版本',
    `sequence_no` int NOT NULL COMMENT '工序顺序',
    `process_code` varchar(50) NOT NULL COMMENT '工序编码',
    `process_name` varchar(100) NOT NULL COMMENT '工序名称',
    `process_type` tinyint NOT NULL COMMENT '工序类型：1=组装 2=检测 3=包装 4=返修',
    `station_code` varchar(50) DEFAULT NULL COMMENT '默认工位编码',
    `station_name` varchar(100) DEFAULT NULL COMMENT '默认工位名称',
    `standard_hours` decimal(10,2) DEFAULT NULL COMMENT '标准工时',
    `is_quality_gate` tinyint NOT NULL DEFAULT 0 COMMENT '是否质检节点：0=否 1=是',
    `inspection_type` varchar(30) DEFAULT NULL COMMENT '检验类型：process/final/AOI/ICT/FCT/recheck',
    `inspection_config` text COMMENT '检验项目、标准值、公差、方法等JSON配置',
    `sop_file` varchar(200) DEFAULT NULL COMMENT '作业指导书路径',
    `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态：0=停用 1=启用',
    PRIMARY KEY (`id`),
    KEY `idx_process_route_model` (`product_model_id`),
    CONSTRAINT `fk_process_route_model` FOREIGN KEY (`product_model_id`) REFERENCES `product_model` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工艺路线表';

CREATE TABLE IF NOT EXISTS `production_order` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `order_no` varchar(50) NOT NULL COMMENT '生产工单编号',
    `product_model_id` bigint NOT NULL COMMENT '产品型号ID',
    `bom_version` varchar(20) NOT NULL COMMENT '绑定BOM版本',
    `route_version` varchar(20) NOT NULL COMMENT '绑定工艺路线版本',
    `batch_no` varchar(50) DEFAULT NULL COMMENT '生产批次号',
    `quantity` int NOT NULL COMMENT '工单数量',
    `planned_start_time` datetime DEFAULT NULL COMMENT '计划开始时间',
    `planned_end_time` datetime DEFAULT NULL COMMENT '计划结束时间',
    `delivery_date` date DEFAULT NULL COMMENT '交付日期',
    `line_name` varchar(100) DEFAULT NULL COMMENT '计划产线/班组',
    `source` varchar(50) DEFAULT NULL COMMENT '来源：ERP/manual',
    `priority` tinyint NOT NULL DEFAULT 0 COMMENT '优先级：0=普通 1=加急',
    `planner_id` bigint DEFAULT NULL COMMENT '计划/派工负责人ID',
    `material_ready_status` tinyint NOT NULL DEFAULT 0 COMMENT '物料齐套状态：0=未齐套 1=齐套',
    `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态：0=待配置 1=已接受 2=生产中 3=待终检 4=完成 5=关闭',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_production_order_order_no` (`order_no`),
    KEY `idx_production_order_model` (`product_model_id`),
    KEY `idx_production_order_planner` (`planner_id`),
    CONSTRAINT `fk_production_order_model` FOREIGN KEY (`product_model_id`) REFERENCES `product_model` (`id`),
    CONSTRAINT `fk_production_order_planner` FOREIGN KEY (`planner_id`) REFERENCES `sys_user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='生产工单表';

CREATE TABLE IF NOT EXISTS `production_task` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `task_no` varchar(50) NOT NULL COMMENT '任务单号',
    `order_id` bigint NOT NULL COMMENT '生产工单ID',
    `process_route_id` bigint NOT NULL COMMENT '工艺路线步骤ID',
    `sequence_no` int NOT NULL COMMENT '工序顺序',
    `station_code` varchar(50) DEFAULT NULL COMMENT '实际执行工位',
    `assigned_user_id` bigint DEFAULT NULL COMMENT '指派操作员/班组长ID',
    `planned_quantity` int NOT NULL COMMENT '计划数量',
    `completed_quantity` int NOT NULL DEFAULT 0 COMMENT '已完工数量',
    `defect_quantity` int NOT NULL DEFAULT 0 COMMENT '不良数量',
    `abnormal_type` tinyint DEFAULT NULL COMMENT '异常类型：1=缺料 2=设备 3=质量 4=其他',
    `abnormal_desc` varchar(500) DEFAULT NULL COMMENT '异常描述',
    `abnormal_solution` varchar(500) DEFAULT NULL COMMENT '异常处理措施',
    `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态：0=待开工 1=生产中 2=暂停 3=已完工 4=待质检 5=异常',
    `start_time` datetime DEFAULT NULL COMMENT '实际开始时间',
    `finish_time` datetime DEFAULT NULL COMMENT '实际完成时间',
    `remark` varchar(200) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_production_task_task_no` (`task_no`),
    KEY `idx_production_task_order` (`order_id`),
    KEY `idx_production_task_route` (`process_route_id`),
    KEY `idx_production_task_assignee` (`assigned_user_id`),
    CONSTRAINT `fk_production_task_order` FOREIGN KEY (`order_id`) REFERENCES `production_order` (`id`),
    CONSTRAINT `fk_production_task_route` FOREIGN KEY (`process_route_id`) REFERENCES `process_route` (`id`),
    CONSTRAINT `fk_production_task_assignee` FOREIGN KEY (`assigned_user_id`) REFERENCES `sys_user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='生产任务表';

CREATE TABLE IF NOT EXISTS `work_report` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `report_no` varchar(50) NOT NULL COMMENT '报工单号',
    `task_id` bigint NOT NULL COMMENT '生产任务ID',
    `order_id` bigint NOT NULL COMMENT '生产工单ID',
    `product_sn` varchar(100) DEFAULT NULL COMMENT '产品条码/SN；批量报工可为空',
    `operator_id` bigint NOT NULL COMMENT '操作员ID',
    `station_code` varchar(50) DEFAULT NULL COMMENT '报工工位',
    `report_quantity` int NOT NULL COMMENT '报工数量',
    `qualified_quantity` int NOT NULL COMMENT '合格数量',
    `defect_quantity` int NOT NULL DEFAULT 0 COMMENT '不良数量',
    `actual_hours` decimal(10,2) DEFAULT NULL COMMENT '实际工时',
    `defect_reason` varchar(200) DEFAULT NULL COMMENT '不良原因',
    `report_time` datetime NOT NULL COMMENT '报工时间',
    `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态：0=撤销 1=有效 2=待审核',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_work_report_report_no` (`report_no`),
    KEY `idx_work_report_task` (`task_id`),
    KEY `idx_work_report_order` (`order_id`),
    KEY `idx_work_report_operator` (`operator_id`),
    CONSTRAINT `fk_work_report_task` FOREIGN KEY (`task_id`) REFERENCES `production_task` (`id`),
    CONSTRAINT `fk_work_report_order` FOREIGN KEY (`order_id`) REFERENCES `production_order` (`id`),
    CONSTRAINT `fk_work_report_operator` FOREIGN KEY (`operator_id`) REFERENCES `sys_user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='报工记录表';

CREATE TABLE IF NOT EXISTS `inspection_record` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `inspection_no` varchar(50) NOT NULL COMMENT '检验单号',
    `inspection_type` varchar(30) NOT NULL COMMENT '检验类型：process/final/recheck/AOI/ICT/FCT',
    `task_id` bigint DEFAULT NULL COMMENT '生产任务ID',
    `order_id` bigint NOT NULL COMMENT '生产工单ID',
    `product_sn` varchar(100) DEFAULT NULL COMMENT '产品条码/SN',
    `process_route_id` bigint DEFAULT NULL COMMENT '工艺路线步骤ID',
    `standard_snapshot` text COMMENT '检验标准快照JSON，避免标准变更影响历史记录',
    `inspector_id` bigint DEFAULT NULL COMMENT '检验员ID；自动检测可为空',
    `source_type` varchar(20) NOT NULL DEFAULT 'manual' COMMENT '数据来源：manual/equipment',
    `equipment_no` varchar(50) DEFAULT NULL COMMENT '检测设备编号，AOI/ICT/FCT时填写',
    `inspection_time` datetime NOT NULL COMMENT '检验时间',
    `result` tinyint NOT NULL COMMENT '结果：0=不合格 1=合格 2=让步接收 3=报废',
    `measured_data` text COMMENT '实测数据或设备报告JSON',
    `defect_reason` varchar(200) DEFAULT NULL COMMENT '不合格原因',
    `handling_method` tinyint DEFAULT NULL COMMENT '处置方式：1=返修 2=报废 3=让步接收',
    `approval_status` tinyint NOT NULL DEFAULT 0 COMMENT '审批状态：0=无需/待审 1=通过 2=驳回',
    `remark` varchar(200) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_inspection_record_no` (`inspection_no`),
    KEY `idx_inspection_record_task` (`task_id`),
    KEY `idx_inspection_record_order` (`order_id`),
    KEY `idx_inspection_record_route` (`process_route_id`),
    KEY `idx_inspection_record_inspector` (`inspector_id`),
    CONSTRAINT `fk_inspection_record_task` FOREIGN KEY (`task_id`) REFERENCES `production_task` (`id`),
    CONSTRAINT `fk_inspection_record_order` FOREIGN KEY (`order_id`) REFERENCES `production_order` (`id`),
    CONSTRAINT `fk_inspection_record_route` FOREIGN KEY (`process_route_id`) REFERENCES `process_route` (`id`),
    CONSTRAINT `fk_inspection_record_inspector` FOREIGN KEY (`inspector_id`) REFERENCES `sys_user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='检验记录表';

CREATE TABLE IF NOT EXISTS `rework_order` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `rework_no` varchar(50) NOT NULL COMMENT '返修工单号',
    `source_inspection_id` bigint NOT NULL COMMENT '来源检验记录ID',
    `order_id` bigint NOT NULL COMMENT '原生产工单ID',
    `task_id` bigint DEFAULT NULL COMMENT '来源任务ID',
    `product_sn` varchar(100) DEFAULT NULL COMMENT '产品条码/SN',
    `defect_reason` varchar(200) DEFAULT NULL COMMENT '不合格原因',
    `rework_requirement` varchar(500) DEFAULT NULL COMMENT '返修要求',
    `assignee_id` bigint DEFAULT NULL COMMENT '维修责任人ID',
    `deadline` datetime DEFAULT NULL COMMENT '返修截止时间',
    `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态：0=待分发 1=返修中 2=待复检 3=完成 4=关闭',
    `repair_action` varchar(500) DEFAULT NULL COMMENT '维修措施',
    `replaced_material` varchar(500) DEFAULT NULL COMMENT '更换物料摘要',
    `repair_hours` decimal(10,2) DEFAULT NULL COMMENT '维修工时',
    `repair_result` varchar(200) DEFAULT NULL COMMENT '维修结果',
    `repair_time` datetime DEFAULT NULL COMMENT '维修完成时间',
    `recheck_inspection_id` bigint DEFAULT NULL COMMENT '复检记录ID',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_rework_order_no` (`rework_no`),
    KEY `idx_rework_order_source_inspection` (`source_inspection_id`),
    KEY `idx_rework_order_order` (`order_id`),
    KEY `idx_rework_order_task` (`task_id`),
    KEY `idx_rework_order_assignee` (`assignee_id`),
    KEY `idx_rework_order_recheck` (`recheck_inspection_id`),
    CONSTRAINT `fk_rework_order_source_inspection` FOREIGN KEY (`source_inspection_id`) REFERENCES `inspection_record` (`id`),
    CONSTRAINT `fk_rework_order_order` FOREIGN KEY (`order_id`) REFERENCES `production_order` (`id`),
    CONSTRAINT `fk_rework_order_task` FOREIGN KEY (`task_id`) REFERENCES `production_task` (`id`),
    CONSTRAINT `fk_rework_order_assignee` FOREIGN KEY (`assignee_id`) REFERENCES `sys_user` (`id`),
    CONSTRAINT `fk_rework_order_recheck` FOREIGN KEY (`recheck_inspection_id`) REFERENCES `inspection_record` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='返修工单表';
